// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCej3odrBjZPuIM8z4aYDy2At0P4Kaxusc',
    appId: '1:476916085720:web:9757309ba8779c6f81f8ad',
    messagingSenderId: '476916085720',
    projectId: 'my-vocabulary-app-2ed88',
    authDomain: 'my-vocabulary-app-2ed88.firebaseapp.com',
    databaseURL: 'https://my-vocabulary-app-2ed88-default-rtdb.firebaseio.com',
    storageBucket: 'my-vocabulary-app-2ed88.appspot.com',
    measurementId: 'G-SX0SDQR9FY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlgH2H9Q2shKI9ECxP0vuCGRN2ix66XoA',
    appId: '1:476916085720:android:4ee7f079b1b3be0081f8ad',
    messagingSenderId: '476916085720',
    projectId: 'my-vocabulary-app-2ed88',
    databaseURL: 'https://my-vocabulary-app-2ed88-default-rtdb.firebaseio.com',
    storageBucket: 'my-vocabulary-app-2ed88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOaYnbPDcm66XLjin8xU6Oxzkyd2qpzw',
    appId: '1:476916085720:ios:968d434bcfcacfe581f8ad',
    messagingSenderId: '476916085720',
    projectId: 'my-vocabulary-app-2ed88',
    databaseURL: 'https://my-vocabulary-app-2ed88-default-rtdb.firebaseio.com',
    storageBucket: 'my-vocabulary-app-2ed88.appspot.com',
    iosBundleId: 'com.pdp.myVocabularyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAOaYnbPDcm66XLjin8xU6Oxzkyd2qpzw',
    appId: '1:476916085720:ios:98df8dab88ea5c4481f8ad',
    messagingSenderId: '476916085720',
    projectId: 'my-vocabulary-app-2ed88',
    databaseURL: 'https://my-vocabulary-app-2ed88-default-rtdb.firebaseio.com',
    storageBucket: 'my-vocabulary-app-2ed88.appspot.com',
    iosBundleId: 'com.pdp.myVocabularyApp.RunnerTests',
  );
}
